version : "3.0.0"

services:
  nginx:
    image : nginx:latest
    ports:
      - "8080"
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - mariadb
    restart: always
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - "3306"
    restart: always
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - "8000"
    restart: always