version: "3.9"

services:

#-----------------
  nginx:
    image: nginx:phobos
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - word-press:/var/www
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    restart: on-failure

#-----------------
  mariadb:
    image: mariadb:phobos
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
    restart: on-failure
#-----------------
  wordpress:
    image: wordpress:phobos
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - word-press:/var/www
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

volumes:
  word-press:
   driver: local
   driver_opts:
    type: none
    o: bind
    device: "${HOME}/data/word-press"
  mariadb-data:
   driver: local
   driver_opts:
    type: none
    o: bind
    device: "${HOME}/data/mariadb-data"

networks:
  inception:
    name: inception