

version: '3.9'

services:
  
  nginx:
    image: nginx:ares
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - word-press:/var/www
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
  
  
  mariadb:
    image: mariadb:ares
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env 
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
    restart: on-failure
  

  wordpress:
    image: wordpress:ares
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - word-press:/var/www
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure


volumes:
  word-press:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${HOME}/data/wordpress"
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${HOME}/data/mariadb-data"


networks:
  inception:
    name: inception